#WhatsApp Configuration
#Thu Jul 23 19:09:35 IST 2026
whatsapp.accessToken=EAAUyuF4wuTIBSBeQgaNdpJcfDlpgwcJ7x3vkJ3BxSn2XbCM8e9GAKcSMcRzM3hcoDcPHFtauhxOcVNx10aL8ghdCVZCXMZAv3vZCzEGkMdAYqCUuFXQ94OMeVB3GQ65CfeG3Hv9Cdo7slKxnvwrxEZCzkAaGVv5KJuqgyr24YZBr6I387VIYWzQeiLgpaYIf7jk8gKk3bZCHyuGxApFKWiSD28wai1KRLHZCiyq0GnxZC1AzJbYJr8gsmoR77RbIqBZC036xnupyukdXjCqRBt13v
whatsapp.apiVersion=v25.0
whatsapp.phoneNumberId=1132433679963771
